github.com:
    users:
        rauldiazespejo-ctrl:
            oauth_token: ghu_oDzNcDrCy9RN3MOEq1OJhfBm85loVz01FcWx
    user: rauldiazespejo-ctrl
    oauth_token: ghu_oDzNcDrCy9RN3MOEq1OJhfBm85loVz01FcWx
